defaults: &defaults
  docker:
    - image: circleci/clojure:lein-2.8.1-node-browsers

version: 2.1

jobs:
  checkout:
    docker:
      - image: circleci/clojure:lein-2.8.1-node-browsers
    steps:
      - checkout:
          path: metabase-clickhouse-driver
      - run:
          name: Check-out MetaBase Integration Branch
          command: git clone --depth=1 -b $MB_BRANCH $MB_REPO metabase
      - run:
          name: Set up paths
          command: ln -sf metabase-clickhouse-driver metabase/modules/drivers/clickhouse
      - persist_to_workspace:
          root: /home/circleci/
          paths:
            - project/metabase-clickhouse-driver
            - project/metabase
          
  be-tests:
    <<: *defaults
    steps:
      - attach_workspace:
          at: /home/circleci/
      - run:
          name: Run backend unit tests with Java 8
          working_directory: metabase
          command: pwd && ls -l
#          command: lein with-profile +ci test
          no_output_timeout: 5m

  # be-linter-eastwood:
  #   <<: *defaults
  #   steps:
  #     - attach_workspace:
  #         at: /home/circleci/
  #     - run:
  #         name: Run Eastwood linter
  #         working_directory: project/metabase
  #         command: lein with-profile +ci eastwood
  #         no_output_timeout: 5m

workflows:
  version: 2
  build:
    jobs:
      - checkout
      - be-tests:
          requires:
            - checkout
      # - be-linter-eastwood:
      #     requires:
      #       - checkout
