version: 2
jobs:
  build:
    docker:
      - image: circleci/clojure:lein-2.8.1-node-browsers
    steps:
      - checkout
      - run: echo "hello world"
      - run: git clone --depth=1 git@github.com:enqueue/metabase.git
      - run: pwd && ls -l
      