version: 2
jobs:
  build:
    docker:
      - image: circleci/clojure:lein-2.8.1-node-browsers
    steps:
      - checkout:
          path: metabase-clickhouse-driver
      - run: git clone --depth=1 -b $MB_BRANCH $MB_REPO metabase
      - run: pwd && ls -l
      